pcm.!default {
    type plug
    slave {
        pcm "hw:keplerc60,0"
        rate 48000
        channels 2
        format S16_LE
    }
}

pcm.!sysdefault {
    type plug
    slave {
        pcm "hw:keplerc60,0"
        rate 48000
        channels 2
        format S16_LE
    }
}

ctl.!default {
    type hw
    card keplerc60
}

ctl.!sysdefault {
    type hw
    card keplerc60
}
